---
- name: Deploy Application
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
